<?php
namespace backend\widgets;


use backend\models\Menu;
use yii\bootstrap\Widget;
use yii\bootstrap\NavBar;
use yii\bootstrap\Nav;
use Yii;

class MenuWidget extends Widget{
    public function init()
    {
        parent::init();
    }

    public function run()
    {
        NavBar::begin([
            'brandLabel' => '京西西商城后台管理',
            'brandUrl' => Yii::$app->homeUrl,
            'options' => [
                'class' => 'navbar-inverse navbar-fixed-top',
            ],
        ]);
        $menuItems = [
            ['label' => '首页', 'url' => ['/user/login']],
        ];
        if (Yii::$app->user->isGuest) {
            $menuItems[] = ['label' => '登陆', 'url' =>Yii::$app->user->loginUrl];
        } else {
            $menuItems[] = ['label' => '注销('.Yii::$app->user->identity->username.')', 'url' => ['user/logout']];
            //获取所有一级菜单
            $menus = Menu::findAll(['parent_id'=>0]);
            foreach ($menus as $menu){
                $item = ['label'=>$menu->label,'items'=>[]];
                foreach ($menu->children as $child){
                    if(Yii::$app->user->can($child->url)){
                        $item['items'][] = ['label'=>$child->label,'url'=>[$child->url]];
                    }

                }
                //如果该一级菜单没有子菜单，就不显示
                if(!empty($item['items'])){
                    $menuItems[] = $item;
                }

            }
        }
        echo Nav::widget([
            'options' => ['class' => 'navbar-nav navbar-right'],
            'items' => $menuItems,
        ]);
        NavBar::end();

        parent::run(); // TODO: Change the autogenerated stub
    }
}